version: "3"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 127.0.0.1:${MONGODB_PORT:-27017}:${MONGODB_PORT:-27017}
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  chatgpt_telegram_bot_pro:
    command: python3 run.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo

  mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo

  jupyter:
    command: jupyter notebook --ip=0.0.0.0 --port ${JUPYTER_PORT} --allow-root --no-browser --NotebookApp.token='${JUPYTER_TOKEN}'
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - ${JUPYTER_PORT:-8888}:${JUPYTER_PORT:-8888}
  